### ISSUE TITLE
Possible misunderstranding in the tutorial

### ISSUE THREAD

**Issue by wilhem** [emanuelhuber/RGPR#35]
Thank for your reply. That's clear the question.

But I found another possible misunderstanding regarding the function `dewow()`
In the wiki it is reported that:

> **Dewow**

> Remove the low-frequency components (the so-called “wow”) of the GPR record using:
> 
>     a running median filter (type = "runnmed")
>     a running mean filter (type = "runmean")
>     a Gaussian filter (type = "Gaussian")
> 
> For the two first cases, the argument w is the length of the filter **in time units**.

But looking at the help

`?dewow`

I get:

> w	[numeric(1)] If type = runmed, MAD or runmean, window length of the filter **in trace unit**; If type = Gaussian, standard deviation in trace unit. If w = NULL, w is estimated as five times the wavelength corresponding to the maximum frequency of x (estimated with spec)

Now it is not clear to me what _w_ should be. 

Let's say I have in my function `w = 5` (time unit [ns]).
Does it mean that the window length of the filter goes from 0 _ns_ to 5 _ns_ all over the traces?
Or does it mean, that the window length of the filter for every _n_ trace [n-5, n-4, n-3, ...0, n+1, n+2,.., n+5] goes from 0 _ns_ till the end of the vertical time windows?

Regards

_Originally posted by @wilhem in https://github.com/emanuelhuber/RGPR/issues/33#issuecomment-667663670_

**Comment by emanuelhuber** [comment]
Hello Wilhem

Thank you for noticing this inconsistency. The help page of the function `dewow()` is the most correct. The argument `w` has to be given in *trace unit*. Though *trace unit* may not be the best term, it means either time unit (if the data are in time unit) or depth unit (e.g. after a migration or time-to-depth conversation).
The unit is returned by `depthunit` (also not the best term because `depthunit` can return a time unit, e.g., `ns`).

This inconsistency will be corrected in the develop version of RGPR. I will update the tutorial as well as the help page of `dewow()`.

> Does it mean that the window length of the filter goes from 0 ns to 5 ns all over the traces?

Yes (if your data were collected as a function of time).
